### ISSUE TITLE
search_mons.php

### ISSUE THREAD

**Issue by Speedyhome72** [bbdoc/PoracleWeb#133]
in search_mons.php change
include_once "db_mad.php"
with the same in header
if (isset($scan_dbtype) && $scan_dbtype == "MAD") {
    include_once "./include/db_mad.php";
}
if (isset($scan_dbtype) && $scan_dbtype == "RDM") {
    include_once "./include/db_rdm.php";
}

**Comment by bbdoc** [comment]
Corrected in latest dev
