### ISSUE TITLE
Don't allow users to set PvP tracking to GL and UL simultaneously

### ISSUE THREAD

**Issue by ColdShadow80** [bbdoc/PoracleWeb#17]
Prevent users from selecting both leagues tracking simultaneously, since this will result in no notifications since no pokemon will fit both rankings simultaneously .
This is a contradiction and my sugestion is that this should be:
Blocked by a warning
or
User should be forced to select one of the leagues (dropdown or bullet or another user friendly selector)
or 
unfold user tracking command into 2 diferent trackings when submitting??? (this would probably be overkill and too much of a development hasle)

**Comment by bbdoc** [comment]
Solved with PvP2.
