### ISSUE TITLE
Navigation bar up top to help "jump" to sections

### ISSUE THREAD

**Issue by t00fan** [bbdoc/PoracleWeb#2]
A navigation bar up top on the main page will help to jump to relevant sections like Monsters, Raids, Eggs, Invasion, Quests more easily for user who have a long list of monster tracking.

**Comment by ColdShadow80** [comment]
This is probably resolved / obsolete by the recent layout change.

**Comment by bbdoc** [comment]
Indeed resolved as this has been included in new design
