### ISSUE TITLE
Undefined index: pokemon_id

### ISSUE THREAD

**Issue by jepke** [bbdoc/PoracleWeb#21]
```
FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: pokemon_id in /opt/poracleweb/index.php on line 809"
```
besides throwing errors in the log not really a problem. Only happens if you track raid eggs

**Comment by bbdoc** [comment]
Solve with f0430eef1a5e1f85d281d648d5a85c2923f78be2
