### ISSUE TITLE
Access restrictions

### ISSUE THREAD

**Issue by acocalypso** [bbdoc/PoracleWeb#3]
I would like to have the possibility to restrict the access on guild and role basis.

User must be member on guild foo and needs role bar.

**Comment by bbdoc** [comment]
Access is already restricted on Poracle side. So if a user is not allowed he will either be removed from the database or be admin_disabled.

Does it mean you want to block access to PoracleWeb when user is admin disabled ? 

At the moment user can still access but will get a warning message. So they know they can set up their trackings but won't receive any alarm anyway.

**Comment by bbdoc** [comment]
You now have an option to disallow access if user is admin_disabled... so you should use PoracleJS settings in order to disallow users based on your guilds/roles, and it will reflect in PoracleWeb.
