### ISSUE TITLE
A config option to disable the location button

### ISSUE THREAD

**Issue by ccev** [bbdoc/PoracleWeb#34]
Since locations require a nominatim server and I don't have one set up, It'd be cool if I could disable the button.

**Comment by bbdoc** [comment]
I will think about it... but then all distance related stuff would also need to be disabled as it would confuse people.

Some other users only use location and would like to disable areas instead ;-)

**Comment by ccev** [comment]
I thought about removing distance as well, but users can still set their location with `!location` in the bot.

The best option would be to have a map where you can pick the location, I think. But I assume that takes some time and until then, I just want to disable the button

**Comment by bbdoc** [comment]
So more globally this is something I already had in mind. My idea is to : 

- Allow to disable areas for people who don't use it.
- Allow to disable location for people who don't use it.
- Add a button to let users set their location based on their current GPS position (assuming they authorize the app to access their position of course as this is purely client stuff).

Letting people chose their location on a map would be cool but probably a lot more complicated to put in place but if they can at least use their current position, that would tacke cases where no nominatim is available.

I will work on that soon ;-)

**Comment by bbdoc** [comment]
Locations and Areas can now be disabled in config with latest commits.

Disabling Location will also disable all distance settings.
