### ISSUE TITLE
[Bug] Not being able to add raid bosses

### ISSUE THREAD

**Issue by Pogodenhelder** [bbdoc/PoracleWeb#37]
running latest version im not being able to select any raid bosses.
![Schermafbeelding 2021-01-04 om 17 31 05](https://user-images.githubusercontent.com/35499601/103556842-a687e080-4eb2-11eb-8023-8a91488ed4ab.png)

as somebody mentioned on discord it might be related to
https://github.com/bbdoc/PoracleWeb/commit/2f5b6b58fa77f5bcb5aefd8bee4edcedc1d45ada

**Comment by bbdoc** [comment]
You probably didn't configure your scanner DB correctly.

**Comment by Pogodenhelder** [comment]
If that was the case then why am i able to select rewards from quests? 
As far as i know those are linked..
![Uploading Schermafbeelding 2021-01-05 om 16.02.37.png…]()

**Comment by Pogodenhelder** [comment]
Just trying to add eggs as well. 
Problem is there is no confirmation box as well.

![Schermafbeelding 2021-01-05 om 16 08 28](https://user-images.githubusercontent.com/35499601/103662469-4788a100-4f70-11eb-915f-c0e622ac277c.png)

**Comment by bbdoc** [comment]
Which clearly show there is an issue on the select as the page stops there... Let's move this discussion to discord as it will be easier to help your and it works for most people.
