### ISSUE TITLE
Pressing enter while editing causes alert to delete

### ISSUE THREAD

**Issue by georgeherby** [bbdoc/PoracleWeb#55]
When I am editing a config for a pokemon I am typing in the IV and rather than clicking on the Update I am pressing the enter key to Update. This, however, seems to delete the alert (without any confirmation dialogue) rather than confirming the update. I would expect the enter key to do the positive action, i.e. Update. 

Also, I would have expected the delete to have some sort of confirmation rather than just deleting.

Steps to recreate:
- Edit existing alert
- Enter a value in the IV (leaving the cursor in the box)
- Press enter key
- Alert is deleted rather than updated

This is the view I was on when I found the bug.
![image](https://user-images.githubusercontent.com/21989833/105019281-d3ed9600-5a3d-11eb-8df7-4b39f2b9046e.png)

**Comment by bbdoc** [comment]
Delete button has been removed from Edit modal as it's now already available on homepage.
