### ISSUE TITLE
settings are saved, even when not choosing to save

### ISSUE THREAD

**Issue by philcerf** [bbdoc/PoracleWeb#56]
Hey.

In the settings dialogue, if one changes a setting and leaves it without storing (e.g. via ESC), the setting seems to be still saved.

Cheers

**Comment by bbdoc** [comment]
There is no way settings could be saved with pushing the update button... it's a form action so if you don't click it won't start updating anything in DB. The only thing that is updated as soon as you click are languages...If you close and reopen the dialog without refreshing the page, it will still show your selection as it's the same page, but that's normal behaviour. Doesn't mean anything has been updated if you didn't click the update button.

Please describe EXACTLY your issue when you have one, and please first mention it on discord before opening issues on non-confirmed behaviour on GitHub.
