### ISSUE TITLE
Poracle’s defaultTemplateName ignored

### ISSUE THREAD

**Issue by philcerf** [bbdoc/PoracleWeb#66]
Hey.

With:
https://github.com/KartulUdus/PoracleJS/commit/96869c2d0a17ae71ada1f89a6c1fe632386f1ca8

Poracle allows to specify a default name for templates, that is used for any rules where the user doesn’t explicitly set the template.
Previously, this was hardcoded to the number `1`.

In PoracleWeb, this is still hardcoded at `1` and thus users may get their rules added to the DB with a wrong or non-existent value.

Cheers.

**Comment by bbdoc** [comment]
This will be solved in the new_ui branch that will be pushed soon ;-)

**Comment by bbdoc** [comment]
Implemented
