### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by reedy** [bbdoc/PoracleWeb#7]
Add a composer.json (PR for some parts of this incoming)

Stuff that needs adding:
- [ ] Add basic composer.json #8
- [ ] Add License to composer.json - #6
- [ ] Add required PHP version to composer.json

**Comment by bbdoc** [comment]
Solved with PR #8

**Comment by reedy** [comment]
Not finished :)

 #6 still needs doing, and then the "license" field of composer.json updating

And we need to at least define a PHP version in composer.json, probably a section like the below to it

```
	"require": {
		"php": ">- 7.0.0"
	},
```

I doubt you're targetting or really support less than PHP 7.0. PHP 7.2 is already EOL, and 7.3 is in security support only - https://www.php.net/supported-versions.php
